-- SHOW DATABASES;
-- use college;
-- show tables;
-- SELECT *
-- from courses;
-- SELECT Course_ID,
--     Course_Name
-- from courses;
-- SELECT count(Course_Name)
-- FROM courses
-- GROUP BY Dept_ID
-- HAVING max(Course_ID) > 5
-- ORDER BY Dept_ID ASC;
-- SELECT *
-- FROM courses;
-- UPDATE courses
-- set Course_Name = "Generative AI"
-- WHERE Course_Name = "Robotics" ;
-- SELECT * from courses;

-- Delete from courses where Course_ID = 512;
-- SELECT * from courses;
-- ALTER TABLE courses add column fees int;
-- UPDATE courses SET fees = 25000 WHERE Course_ID >100;
-- SELECT * from courses;

-- ALTER TABLE courses Drop column fees;

-- -🟢 Level 1: Basic Retrieval (1-40)
-- Focus: SELECT, WHERE, DISTINCT, LIMIT, ORDER BY

-- Select all columns from the Users table.

-- Find the names of all products with a price greater than $500.

-- List all unique cities where users reside.

-- Show the top 5 most expensive products.

-- Find all users who joined in the year 2025.

-- Get all orders with a "Pending" status.

-- List products that have zero stock.

-- Find users whose last name starts with 'S'.

-- Calculate the 10% tax for every product price.

-- List all categories sorted alphabetically.

-- (11-40): Repeat variations using different filters (e.g., price ranges, specific dates, specific email domains).

-- 🟡 Level 2: Aggregations & Grouping (41-80)
-- Focus: COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING

-- What is the total number of users?

-- Find the average price of products in each category.

-- How many orders were placed by each user?

-- Find categories that have more than 10 products.

-- What is the total revenue generated by the store?

-- Find the highest-rated product (average rating).

-- Count how many reviews each product has received.

-- Find the minimum and maximum price in the "Electronics" category.

-- Show the total quantity sold for each ProductID.

-- (50-80): Group by city, month, or order status to find trends and counts.

-- 🟠 Level 3: Joins & Relationships (81-120)
-- Focus: INNER, LEFT, RIGHT, FULL OUTER JOIN

-- Display OrderIDs alongside the FirstName of the user who placed them.

-- List all products and their corresponding CategoryName.

-- Show all OrderItems including the ProductName for each item.

-- Find users who have never placed an order (LEFT JOIN).

-- Join Reviews and Products to show product names with their ratings.

-- List all orders and the total number of items in each order.

-- Find the most popular category based on the number of products sold.

-- Get a list of users and the total amount they have spent across all orders.

-- Show products that have never been reviewed.

-- (90-120): Multi-table joins (e.g., link Users to OrderItems via Orders).

-- 🔴 Level 4: Subqueries & CTEs (121-160)
-- Focus: Subqueries in WHERE/FROM, Common Table Expressions (WITH)

-- Find products with a price higher than the average product price.

-- Identify users who spent more than the average total order amount.

-- Use a CTE to list the top 3 spending users.

-- Find products that were never bought in the last 30 days.

-- List users who bought products from at least three different categories.

-- Use a subquery to find the name of the category with the most items.

-- Find the second most expensive product without using LIMIT.

-- Create a temporary result set of "High Value Orders" (> $1000).

-- Find employees (if added) who earn more than their managers.

-- (130-160): Complex filtering using IN, EXISTS, and ANY.

-- 🟣 Level 5: Window Functions & Advanced (161-200)
-- Focus: ROW_NUMBER, RANK, LEAD/LAG, CASE, DATA MODIFICATION

-- Rank products by price within each category.

-- Find the running total of sales ordered by date.

-- Use CASE to label products as "Cheap," "Mid-range," or "Premium."

-- Find the difference in price between a product and the one ranked immediately below it.

-- Select the 3rd order placed by every user.

-- Update all "Pending" orders to "Cancelled" if they are older than 30 days.

-- Delete users who haven't logged in for 2 years (if LastLogin existed).

-- Calculate the month-over-month growth in revenue.

-- Identify "duplicate" email addresses in the Users table.

-- (170-200): Data cleaning (TRIM, COALESCE), Indexing theory, and View creation.